version: "3.6"
services:
  elastic:
    container_name: bcd-elastic
    image: bakingbad/bcdhub-elastic:${TAG:-latest}
    build:
      context: .
      dockerfile: elastic.dockerfile
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data    
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    env_file:
      - .env
    ports:
      - "127.0.0.1:9300:9300"
      - "127.0.0.1:9200:9200"
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"

  mq:
    container_name: bcd-mq
    image: rabbitmq:latest
    restart: always
    volumes:
      - mqdata:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    logging: *my-logging        

  db:
    container_name: bcd-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    logging: *my-logging

  api:
    container_name: bcd-api
    restart: always
    image: bakingbad/bcdhub-api:${TAG:-latest}
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - db
    ports:
      - 127.0.0.1:14000:14000
    volumes:
      - /etc/bcd:/etc/bcd
    logging: *my-logging

  indexer:
    container_name: bcd-indexer
    restart: always
    image: bakingbad/bcdhub-indexer:${TAG:-latest}
    build:
      context: .
      dockerfile: cmd/indexer/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
      - metrics
    volumes:
      - /etc/bcd:/etc/bcd
    logging: *my-logging

  metrics:
    container_name: bcd-metrics
    restart: always
    image: bakingbad/bcdhub-metrics:${TAG:-latest}
    build:
      context: .
      dockerfile: cmd/metrics/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
      - db
    logging: *my-logging

volumes:
  esdata:
  mqdata:
  db:
    driver: local
