share:
    path: /home/${USER}/.bcd

sentry:
    environment: development
    uri: ${SENTRY_DSN}
    debug: true

elastic:
    uri: http://127.0.0.1:9200

db:
    conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=bcd password=${POSTGRES_PASSWORD} sslmode=disable"

oauth:
    state: ${OAUTH_STATE_STRING}
    jwt:
        secret: ${JWT_SECRET_KEY}
        redirect_url: http://localhost:8080/welcome
    github:
        client_id: ${GITHUB_CLIENT_ID}
        secret: ${GITHUB_CLIENT_SECRET}
        callback_url: http://localhost:14000/v1/oauth/github/callback
    gitlab:
        client_id: ${GITLAB_CLIENT_ID}
        secret: ${GITLAB_CLIENT_SECRET}
        callback_url: https://localhost:14000/v1/oauth/gitlab/callback

seed:
    user:
      login: "sandboxuser"
      name: "Default User"
      avatar_url: "https://services.tzkt.io/v1/avatars/bcd"
      token: ""
    subscriptions:
        - address: "tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"
          network: "sandboxnet"
        - address: "tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6"
          network: "sandboxnet"
    aliases:
        - alias: "Alice"
          network: "sandboxnet"
          address: "tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"
        - alias: "Bob"
          network: "sandboxnet"
          address: "tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6"
    accounts:
        - private_key: "privatekey"
          public_key_hash: "publickeyhash"
          network: "sandboxnet"

api:
    bind: "127.0.0.1:14000"
    oauth:
        enabled: true
    sentry:
        enabled: false
    networks:
        - mainnet
        - carthagenet
        - zeronet
        - babylonnet
    seed:
      enabled: true
