share:
    path: /home/${USER}/.bcd

sentry:
    environment: development
    uri: ${SENTRY_DSN}
    debug: true

elastic:
    uri: http://127.0.0.1:9200

rabbitmq:
    uri: "amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@127.0.0.1:5672/"

indexer:
    sentry:
        enabled: false
    networks:
        mainnet:
          boost: tzkt
        # carthagenet:
        #   boost: tzkt
        # zeronet:
        #   boost: tzkt
